version: '3.4'

services:
  SonarQube:
    image: sonarqube:community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonartest
      SONAR_JDBC_PASSWORD: sonartest
    volumes:
      - ./sonar/data:/opt/SonarQube/data
      - ./sonar/extensions:/opt/SonarQube/extensions
      - ./sonar/logs:/opt/SonarQube/logs
    ports:
      - "80:9000"
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonartest
      POSTGRES_PASSWORD: sonartest
      POSTGRES_DB: sonar
    volumes:
      - ./psql:/var/lib/postgresql
      - ./psql/data:/var/lib/postgresql/data